2019-04-22 21:51:05,366 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Restarting with stat 
2019-04-22 21:52:48,615 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) 
2019-04-22 21:52:48,640 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Restarting with stat 
2019-04-22 21:52:50,124 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | WARNING |  * Debugger is active! 
2019-04-22 21:52:50,136 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Debugger PIN: 165-957-176 
2019-04-22 21:52:54,759 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:52:54] "GET / HTTP/1.1" 200 - 
2019-04-22 21:52:57,671 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:52:57] "GET /favicon.ico HTTP/1.1" 404 - 
2019-04-22 21:53:13,075 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:53:13] "GET / HTTP/1.1" 200 - 
2019-04-22 21:53:13,134 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:53:13] "GET /data1? HTTP/1.1" 200 - 
2019-04-22 21:53:21,216 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:53:21] "GET / HTTP/1.1" 200 - 
2019-04-22 21:53:37,468 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:53:37] "GET / HTTP/1.1" 200 - 
2019-04-22 21:55:52,356 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Detected change in '/home/vikas/Documents/SPEflask/main.py', reloading 
2019-04-22 21:55:52,456 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Restarting with stat 
2019-04-22 21:55:57,443 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | WARNING |  * Debugger is active! 
2019-04-22 21:55:57,443 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Debugger PIN: 479-068-565 
2019-04-22 21:56:01,481 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Detected change in '/home/vikas/Documents/SPEflask/main.py', reloading 
2019-04-22 21:56:01,636 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Restarting with stat 
2019-04-22 21:56:03,369 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | WARNING |  * Debugger is active! 
2019-04-22 21:56:03,370 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Debugger PIN: 278-356-905 
2019-04-22 21:56:23,606 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:56:23] "GET / HTTP/1.1" 200 - 
2019-04-22 21:56:27,783 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:56:27] "GET / HTTP/1.1" 200 - 
2019-04-22 21:56:37,636 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) 
2019-04-22 21:56:37,637 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Restarting with stat 
2019-04-22 21:56:39,000 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | WARNING |  * Debugger is active! 
2019-04-22 21:56:39,000 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Debugger PIN: 701-082-947 
2019-04-22 21:57:17,145 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:57:17] "GET / HTTP/1.1" 200 - 
2019-04-22 21:58:08,542 | /home/vikas/anaconda3/lib/python3.6/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 21:58:08] "GET /data1? HTTP/1.1" 200 - 
2019-04-22 22:30:23,963 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) 
2019-04-22 22:30:23,965 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Restarting with stat 
2019-04-22 22:30:25,096 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | WARNING |  * Debugger is active! 
2019-04-22 22:30:25,113 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Debugger PIN: 321-801-135 
2019-04-22 22:30:57,600 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 22:30:57] "GET / HTTP/1.1" 200 - 
2019-04-22 22:30:57,966 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 22:30:57] "GET /favicon.ico HTTP/1.1" 404 - 
2019-04-22 22:31:05,091 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 22:31:05] "GET /data2 HTTP/1.1" 200 - 
2019-04-22 23:37:43,400 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) 
2019-04-22 23:37:43,434 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Restarting with stat 
2019-04-22 23:37:44,421 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | WARNING |  * Debugger is active! 
2019-04-22 23:37:44,442 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO |  * Debugger PIN: 339-319-685 
2019-04-22 23:37:46,833 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 23:37:46] "GET / HTTP/1.1" 200 - 
2019-04-22 23:38:00,381 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 23:38:00] "GET /data2 HTTP/1.1" 200 - 
2019-04-22 23:38:02,608 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 23:38:02] "GET /taximonthly HTTP/1.1" 200 - 
2019-04-22 23:38:19,675 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 23:38:19] "GET /data1 HTTP/1.1" 200 - 
2019-04-22 23:38:21,197 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 23:38:21] "GET /uberbusiness HTTP/1.1" 200 - 
2019-04-22 23:38:21,341 | /home/naman/yes/lib/python2.7/site-packages/werkzeug/_internal.py:88 | _log | INFO | 127.0.0.1 - - [22/Apr/2019 23:38:21] "GET /static/uber_business.png HTTP/1.1" 200 - 
2019-04-24 17:15:09,568 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | INFO |  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit) 
2019-04-24 17:15:09,568 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | INFO |  * Restarting with stat 
2019-04-24 17:15:10,863 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | WARNING |  * Debugger is active! 
2019-04-24 17:15:11,137 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | INFO |  * Debugger PIN: 232-181-503 
2019-04-24 17:15:23,946 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | INFO | 127.0.0.1 - - [24/Apr/2019 17:15:23] "GET /taxiweek HTTP/1.1" 200 - 
2019-04-24 17:15:24,096 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | INFO | 127.0.0.1 - - [24/Apr/2019 17:15:24] "GET /static/taxi_week.png HTTP/1.1" 200 - 
2019-04-24 17:15:27,631 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | INFO | 127.0.0.1 - - [24/Apr/2019 17:15:27] "GET /uberbusiness HTTP/1.1" 200 - 
2019-04-24 17:15:27,789 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | INFO | 127.0.0.1 - - [24/Apr/2019 17:15:27] "GET /static/uber_business.png HTTP/1.1" 200 - 
2019-04-24 17:15:34,288 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | INFO | 127.0.0.1 - - [24/Apr/2019 17:15:34] "GET /taxiweather HTTP/1.1" 200 - 
2019-04-24 17:15:54,706 | /usr/local/lib/python3.6/dist-packages/werkzeug/_internal.py:122 | _log | INFO | 127.0.0.1 - - [24/Apr/2019 17:15:54] "GET /uberweather HTTP/1.1" 200 - 
